version: '3.8'

networks:
  global_network:
    external: true

services:
  disha_portfolio:
    image: 'node:lts-slim'
    container_name: disha_portfolio
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -  "5173:5173"
      # -  "3003:3003"
    networks:
      - global_network

  # redis:
  #   image: 'redis:alpine'
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - global_network
